# Competitions (galas)

All swimmers are encouraged to take part in stage-appropriate galas as they are fun, exciting, motivating and excellent for development.

Our annual competition calendar tends to include four home galas (which all swimmers are expected to enter where possible) and several away galas in the North East Region.
You are not expected to enter every gala, and you can discuss which ones would suit your swimmer with their coach at any time.

The competition season runs from about August to June.

For every gala, be it home or away, a (DBS checked) Team Manager (often more than one) is required to look after the swimmers, organise itineraries and generally help with the smooth running of the event.
Where team transport is available for attending away galas, new swimmers can be confident that the Team Managers are there to look out for them, and their whole team will make sure they have a positive, fun experience.

## What happens at a gala?

Swimmers make their way to the venue ready to start the group warm up at the scheduled time.
They will have a team area on poolside where they will rest between races, eat and drink something, play games (no electronic devices allowed) or read books.
Team Managers and Marshalls will ensure each swimmer is ready to compete when their events come around.
There is often access to a 'cool down pool' provided during the event so that athletes can keep their muscles warm between races and cool down after intense swimming.

Typical kit needed for a gala includes:

- swimming costume
- goggles (plus a spare pair)
- towels (one for poolside, one for after)
- team swim cap
- team T-shirt
- enough healthy food and water for the duration of the event
- something to occupy them poolside between races (e.g. book, card games etc.)

## Gala levels

Galas range from 'just for fun' unlicensed events, right up to professional National extravaganzas. 
You can tell how 'serious' a gala is by its 'level', which dictates how official is it, what its results times can be used for and who can enter.
Level 4 galas require a license, but are the entry-level events.
Level 3 galas require specific qualified officials to be present, and results can be used for entry to level 2 galas. 
At Alnwick, the galas we host are all level 3 or 4.

### Home galas

The club typically hosts the following galas at the following times of the year.
For all except the Club Championships, other clubs in the region are invited to participate.

- Autumn Invitational (October)
- Distance Time Trial (Level 4, November, for County and Performance Squads) 
- New Year Invitational (January)
- Club Championships (June)

### Away galas

Each year the Competition Secretary along with the Committee will identify externally hosted galas that fit in with the club's existing commitments, and make them available to enter via Swim Manager. 

The coaches will decide which squads should target which galas, to enable them to obtain the relevant qualifying times for future events and provide a range of different experiences for the squads.

Typically, the galas where entry is encouraged for all junior swimmers include:

#### Newcastle Swim Team's Shrip Galas
Held at Tynemouth pool at vaious times throughout the season, these fun events are a great introduction to competitions for younger (8-12 years) swimmers. These are level 4 galas.

#### Mini Morpeth Meet
A super fun, super friendly introduction to racing, this unlicensed event usually occurs in early Winter.

#### South Tyneside Meets
A level 3 gala held in South Shields for swimmers 9+.
Often run in Spring and Autumn.

#### Durham Medley Challenge
The Durham Medley Challenge (Level 3) is a little different to the usual galas. 
For the flat fee of £25 per swimmer, each swimmer is entered into either 50m or 100m events in each stoke depending on their age on the day.

#### Juniour ('Diddy') League
Teams from all over the North East compete for the title of Junior League Champions.
The competition is fun, exciting, very competitive and very, very loud with a mixture of individual and team relay events.
The league consists of 3 divisions and teams are promoted and relegated between the divisions depending on where they finish.
Typically there are two or three 'heats' before the Junior League Finals, held in September.
These galas are usually NOT added to Swim Manager but are organised separately.

----

Other galas require swimmers to have achieved qualifying times to enter, and may change from year to year.
You can find out more about each upcoming competition on our competition calendar which is emailed out to all
parents at the start of the new season.

If you have questions about any of the above, please contact the [competition secretary](mailto:competitionsecretary@alnwickdolphins.com).

