# How to join Alnwick Dolphins

All swimmers enter the club by first having a short Swimming Taster Session.
Times and dates for these are advertised on [our website](https://www.alnwickdolphins.com/join/) and on the notice boards at poolside.
If you wish to take part in a taster session, please [register your interest](https://www.alnwickdolphins.com/join/) for the next available session.

## How fit/capable do I need to be to try out?

To flourish at Alnwick Dolphins, new swimmers need to be confident in the water, typically having completed the equivalent of Stage 6 of the Swim England Swimming Development Programme, and being at least 7 years old.

## What happens at a taster session?

Please arrive at your session promptly so the group can start together. 
No extra kit is needed, just your usual swimming costume and goggles.
You will be welcomed by the coach and the session will be explained to you.

You will be asked to show the coach several swim strokes, but you don't need to be fast, or be able to swim a very long way.
We are looking for potential, not the finished product!
The coaches will be appraising the swimmer for their physical abilities as well as how they cope with the instructions given.

After the Taster Session, the coaches will convene to discuss each
swimmers performance and determine who they feel is ready to join the club.
You will be notified by email the result of the Taster Session within 2 weeks.
But don't worry if you don't make it this time, you can always try again at a future Taster Session!

## 🚀 I got in!! Now what?

To become a member of the club, you will be asked to 

- read and sign a swimmers code of conduct
- read and sign a parent/carers code of conduct
- register with [Swim England as a Club Compete member](https://www.swimming.org/members/category-two-club-membership/) (currently £37.35 annually, this enables you to compete at licensed events, provides insurance and other member benefits)
- sign up to use [Swim Manager](swim-manager.qmd), adding your bank details to enable payments to be taken monthly.

Once signed up, check your training timetable (which you can find on Swim Manager), ensure you have the kit you need, then get started on your Alnwick Dolphins journey! 🐬

Have a look at the [training page](training.qmd) to see what goes on at a typical training session.
 